FROM ubuntu
RUN apt-get update
RUN apt-get install -y libtool libtool-bin autoconf automake cmake g++ unzip curl
RUN apt-get install -y pkg-config curl git gdb python
#RUN apt-get install -y pkg-config ninja


